// <auto-generated />
using System;
using H3Project.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace H3Project.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250109090714_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("GenresId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("GenreMovie");

                    b.HasData(
                        new
                        {
                            GenresId = 1,
                            MoviesId = 1
                        },
                        new
                        {
                            GenresId = 2,
                            MoviesId = 1
                        },
                        new
                        {
                            GenresId = 2,
                            MoviesId = 2
                        },
                        new
                        {
                            GenresId = 3,
                            MoviesId = 3
                        });
                });

            modelBuilder.Entity("H3Project.Data.Models.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Movie St",
                            Name = "Grand Cinema"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Central Ave",
                            Name = "Downtown Cinema"
                        });
                });

            modelBuilder.Entity("H3Project.Data.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Drama"
                        });
                });

            modelBuilder.Entity("H3Project.Data.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "High-speed action",
                            Duration = new TimeSpan(0, 2, 30, 0, 0),
                            ImageUrl = "https://placehold.co/400x600?text=Fast+And+Furious+10",
                            ReleaseDate = new DateOnly(2024, 1, 15),
                            Slug = "fast-and-furious-10",
                            Title = "Fast & Furious 10"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Hilarious comedy",
                            Duration = new TimeSpan(0, 1, 45, 0, 0),
                            ImageUrl = "https://placehold.co/400x600?text=Laugh+Out+Loud",
                            ReleaseDate = new DateOnly(2024, 2, 10),
                            Slug = "laugh-out-loud",
                            Title = "Laugh Out Loud"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Heartfelt drama",
                            Duration = new TimeSpan(0, 2, 10, 0, 0),
                            ImageUrl = "https://placehold.co/400x600?text=Deep+Emotions",
                            ReleaseDate = new DateOnly(2024, 3, 5),
                            Slug = "deep-emotions",
                            Title = "Deep Emotions"
                        });
                });

            modelBuilder.Entity("H3Project.Data.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShowTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TheaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("TheaterId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 12.99m,
                            EndTime = new DateTime(2024, 1, 16, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            ShowTime = new DateTime(2024, 1, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 14.99m,
                            EndTime = new DateTime(2024, 1, 16, 23, 30, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            ShowTime = new DateTime(2024, 1, 16, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 9.99m,
                            EndTime = new DateTime(2024, 2, 11, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 2,
                            ShowTime = new DateTime(2024, 2, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            TheaterId = 2
                        });
                });

            modelBuilder.Entity("H3Project.Data.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("TheaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("TheaterId");

                    b.HasIndex("Row", "Number", "TheaterId")
                        .IsUnique();

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true,
                            Number = 1,
                            Row = "A",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = true,
                            Number = 2,
                            Row = "A",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsAvailable = true,
                            Number = 3,
                            Row = "A",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 4,
                            IsAvailable = true,
                            Number = 4,
                            Row = "A",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 5,
                            IsAvailable = true,
                            Number = 5,
                            Row = "A",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 6,
                            IsAvailable = true,
                            Number = 6,
                            Row = "A",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 7,
                            IsAvailable = true,
                            Number = 7,
                            Row = "A",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 8,
                            IsAvailable = true,
                            Number = 8,
                            Row = "A",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 9,
                            IsAvailable = true,
                            Number = 9,
                            Row = "A",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 10,
                            IsAvailable = true,
                            Number = 10,
                            Row = "A",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 11,
                            IsAvailable = true,
                            Number = 11,
                            Row = "A",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 12,
                            IsAvailable = true,
                            Number = 12,
                            Row = "A",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 13,
                            IsAvailable = true,
                            Number = 1,
                            Row = "B",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 14,
                            IsAvailable = true,
                            Number = 2,
                            Row = "B",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 15,
                            IsAvailable = true,
                            Number = 3,
                            Row = "B",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 16,
                            IsAvailable = true,
                            Number = 4,
                            Row = "B",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 17,
                            IsAvailable = true,
                            Number = 5,
                            Row = "B",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 18,
                            IsAvailable = true,
                            Number = 6,
                            Row = "B",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 19,
                            IsAvailable = true,
                            Number = 7,
                            Row = "B",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 20,
                            IsAvailable = true,
                            Number = 8,
                            Row = "B",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 21,
                            IsAvailable = true,
                            Number = 9,
                            Row = "B",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 22,
                            IsAvailable = true,
                            Number = 10,
                            Row = "B",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 23,
                            IsAvailable = true,
                            Number = 11,
                            Row = "B",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 24,
                            IsAvailable = true,
                            Number = 12,
                            Row = "B",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 25,
                            IsAvailable = true,
                            Number = 1,
                            Row = "C",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 26,
                            IsAvailable = true,
                            Number = 2,
                            Row = "C",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 27,
                            IsAvailable = true,
                            Number = 3,
                            Row = "C",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 28,
                            IsAvailable = true,
                            Number = 4,
                            Row = "C",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 29,
                            IsAvailable = true,
                            Number = 5,
                            Row = "C",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 30,
                            IsAvailable = true,
                            Number = 6,
                            Row = "C",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 31,
                            IsAvailable = true,
                            Number = 7,
                            Row = "C",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 32,
                            IsAvailable = true,
                            Number = 8,
                            Row = "C",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 33,
                            IsAvailable = true,
                            Number = 9,
                            Row = "C",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 34,
                            IsAvailable = true,
                            Number = 10,
                            Row = "C",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 35,
                            IsAvailable = true,
                            Number = 11,
                            Row = "C",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 36,
                            IsAvailable = true,
                            Number = 12,
                            Row = "C",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 37,
                            IsAvailable = true,
                            Number = 1,
                            Row = "D",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 38,
                            IsAvailable = true,
                            Number = 2,
                            Row = "D",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 39,
                            IsAvailable = true,
                            Number = 3,
                            Row = "D",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 40,
                            IsAvailable = true,
                            Number = 4,
                            Row = "D",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 41,
                            IsAvailable = true,
                            Number = 5,
                            Row = "D",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 42,
                            IsAvailable = true,
                            Number = 6,
                            Row = "D",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 43,
                            IsAvailable = true,
                            Number = 7,
                            Row = "D",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 44,
                            IsAvailable = true,
                            Number = 8,
                            Row = "D",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 45,
                            IsAvailable = true,
                            Number = 9,
                            Row = "D",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 46,
                            IsAvailable = true,
                            Number = 10,
                            Row = "D",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 47,
                            IsAvailable = true,
                            Number = 11,
                            Row = "D",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 48,
                            IsAvailable = true,
                            Number = 12,
                            Row = "D",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 49,
                            IsAvailable = true,
                            Number = 1,
                            Row = "E",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 50,
                            IsAvailable = true,
                            Number = 2,
                            Row = "E",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 51,
                            IsAvailable = true,
                            Number = 3,
                            Row = "E",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 52,
                            IsAvailable = true,
                            Number = 4,
                            Row = "E",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 53,
                            IsAvailable = true,
                            Number = 5,
                            Row = "E",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 54,
                            IsAvailable = true,
                            Number = 6,
                            Row = "E",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 55,
                            IsAvailable = true,
                            Number = 7,
                            Row = "E",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 56,
                            IsAvailable = true,
                            Number = 8,
                            Row = "E",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 57,
                            IsAvailable = true,
                            Number = 9,
                            Row = "E",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 58,
                            IsAvailable = true,
                            Number = 10,
                            Row = "E",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 59,
                            IsAvailable = true,
                            Number = 11,
                            Row = "E",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 60,
                            IsAvailable = true,
                            Number = 12,
                            Row = "E",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 61,
                            IsAvailable = true,
                            Number = 1,
                            Row = "F",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 62,
                            IsAvailable = true,
                            Number = 2,
                            Row = "F",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 63,
                            IsAvailable = true,
                            Number = 3,
                            Row = "F",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 64,
                            IsAvailable = true,
                            Number = 4,
                            Row = "F",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 65,
                            IsAvailable = true,
                            Number = 5,
                            Row = "F",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 66,
                            IsAvailable = true,
                            Number = 6,
                            Row = "F",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 67,
                            IsAvailable = true,
                            Number = 7,
                            Row = "F",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 68,
                            IsAvailable = true,
                            Number = 8,
                            Row = "F",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 69,
                            IsAvailable = true,
                            Number = 9,
                            Row = "F",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 70,
                            IsAvailable = true,
                            Number = 10,
                            Row = "F",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 71,
                            IsAvailable = true,
                            Number = 11,
                            Row = "F",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 72,
                            IsAvailable = true,
                            Number = 12,
                            Row = "F",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 73,
                            IsAvailable = true,
                            Number = 1,
                            Row = "G",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 74,
                            IsAvailable = true,
                            Number = 2,
                            Row = "G",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 75,
                            IsAvailable = true,
                            Number = 3,
                            Row = "G",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 76,
                            IsAvailable = true,
                            Number = 4,
                            Row = "G",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 77,
                            IsAvailable = true,
                            Number = 5,
                            Row = "G",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 78,
                            IsAvailable = true,
                            Number = 6,
                            Row = "G",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 79,
                            IsAvailable = true,
                            Number = 7,
                            Row = "G",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 80,
                            IsAvailable = true,
                            Number = 8,
                            Row = "G",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 81,
                            IsAvailable = true,
                            Number = 9,
                            Row = "G",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 82,
                            IsAvailable = true,
                            Number = 10,
                            Row = "G",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 83,
                            IsAvailable = true,
                            Number = 11,
                            Row = "G",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 84,
                            IsAvailable = true,
                            Number = 12,
                            Row = "G",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 85,
                            IsAvailable = true,
                            Number = 1,
                            Row = "H",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 86,
                            IsAvailable = true,
                            Number = 2,
                            Row = "H",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 87,
                            IsAvailable = true,
                            Number = 3,
                            Row = "H",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 88,
                            IsAvailable = true,
                            Number = 4,
                            Row = "H",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 89,
                            IsAvailable = true,
                            Number = 5,
                            Row = "H",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 90,
                            IsAvailable = true,
                            Number = 6,
                            Row = "H",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 91,
                            IsAvailable = true,
                            Number = 7,
                            Row = "H",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 92,
                            IsAvailable = true,
                            Number = 8,
                            Row = "H",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 93,
                            IsAvailable = true,
                            Number = 9,
                            Row = "H",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 94,
                            IsAvailable = true,
                            Number = 10,
                            Row = "H",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 95,
                            IsAvailable = true,
                            Number = 11,
                            Row = "H",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 96,
                            IsAvailable = true,
                            Number = 12,
                            Row = "H",
                            TheaterId = 1
                        },
                        new
                        {
                            Id = 97,
                            IsAvailable = true,
                            Number = 1,
                            Row = "A",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 98,
                            IsAvailable = true,
                            Number = 2,
                            Row = "A",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 99,
                            IsAvailable = true,
                            Number = 3,
                            Row = "A",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 100,
                            IsAvailable = true,
                            Number = 4,
                            Row = "A",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 101,
                            IsAvailable = true,
                            Number = 5,
                            Row = "A",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 102,
                            IsAvailable = true,
                            Number = 6,
                            Row = "A",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 103,
                            IsAvailable = true,
                            Number = 7,
                            Row = "A",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 104,
                            IsAvailable = true,
                            Number = 8,
                            Row = "A",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 105,
                            IsAvailable = true,
                            Number = 9,
                            Row = "A",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 106,
                            IsAvailable = true,
                            Number = 10,
                            Row = "A",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 107,
                            IsAvailable = true,
                            Number = 1,
                            Row = "B",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 108,
                            IsAvailable = true,
                            Number = 2,
                            Row = "B",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 109,
                            IsAvailable = true,
                            Number = 3,
                            Row = "B",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 110,
                            IsAvailable = true,
                            Number = 4,
                            Row = "B",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 111,
                            IsAvailable = true,
                            Number = 5,
                            Row = "B",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 112,
                            IsAvailable = true,
                            Number = 6,
                            Row = "B",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 113,
                            IsAvailable = true,
                            Number = 7,
                            Row = "B",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 114,
                            IsAvailable = true,
                            Number = 8,
                            Row = "B",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 115,
                            IsAvailable = true,
                            Number = 9,
                            Row = "B",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 116,
                            IsAvailable = true,
                            Number = 10,
                            Row = "B",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 117,
                            IsAvailable = true,
                            Number = 1,
                            Row = "C",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 118,
                            IsAvailable = true,
                            Number = 2,
                            Row = "C",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 119,
                            IsAvailable = true,
                            Number = 3,
                            Row = "C",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 120,
                            IsAvailable = true,
                            Number = 4,
                            Row = "C",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 121,
                            IsAvailable = true,
                            Number = 5,
                            Row = "C",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 122,
                            IsAvailable = true,
                            Number = 6,
                            Row = "C",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 123,
                            IsAvailable = true,
                            Number = 7,
                            Row = "C",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 124,
                            IsAvailable = true,
                            Number = 8,
                            Row = "C",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 125,
                            IsAvailable = true,
                            Number = 9,
                            Row = "C",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 126,
                            IsAvailable = true,
                            Number = 10,
                            Row = "C",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 127,
                            IsAvailable = true,
                            Number = 1,
                            Row = "D",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 128,
                            IsAvailable = true,
                            Number = 2,
                            Row = "D",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 129,
                            IsAvailable = true,
                            Number = 3,
                            Row = "D",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 130,
                            IsAvailable = true,
                            Number = 4,
                            Row = "D",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 131,
                            IsAvailable = true,
                            Number = 5,
                            Row = "D",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 132,
                            IsAvailable = true,
                            Number = 6,
                            Row = "D",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 133,
                            IsAvailable = true,
                            Number = 7,
                            Row = "D",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 134,
                            IsAvailable = true,
                            Number = 8,
                            Row = "D",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 135,
                            IsAvailable = true,
                            Number = 9,
                            Row = "D",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 136,
                            IsAvailable = true,
                            Number = 10,
                            Row = "D",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 137,
                            IsAvailable = true,
                            Number = 1,
                            Row = "E",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 138,
                            IsAvailable = true,
                            Number = 2,
                            Row = "E",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 139,
                            IsAvailable = true,
                            Number = 3,
                            Row = "E",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 140,
                            IsAvailable = true,
                            Number = 4,
                            Row = "E",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 141,
                            IsAvailable = true,
                            Number = 5,
                            Row = "E",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 142,
                            IsAvailable = true,
                            Number = 6,
                            Row = "E",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 143,
                            IsAvailable = true,
                            Number = 7,
                            Row = "E",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 144,
                            IsAvailable = true,
                            Number = 8,
                            Row = "E",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 145,
                            IsAvailable = true,
                            Number = 9,
                            Row = "E",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 146,
                            IsAvailable = true,
                            Number = 10,
                            Row = "E",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 147,
                            IsAvailable = true,
                            Number = 1,
                            Row = "F",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 148,
                            IsAvailable = true,
                            Number = 2,
                            Row = "F",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 149,
                            IsAvailable = true,
                            Number = 3,
                            Row = "F",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 150,
                            IsAvailable = true,
                            Number = 4,
                            Row = "F",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 151,
                            IsAvailable = true,
                            Number = 5,
                            Row = "F",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 152,
                            IsAvailable = true,
                            Number = 6,
                            Row = "F",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 153,
                            IsAvailable = true,
                            Number = 7,
                            Row = "F",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 154,
                            IsAvailable = true,
                            Number = 8,
                            Row = "F",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 155,
                            IsAvailable = true,
                            Number = 9,
                            Row = "F",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 156,
                            IsAvailable = true,
                            Number = 10,
                            Row = "F",
                            TheaterId = 2
                        },
                        new
                        {
                            Id = 157,
                            IsAvailable = true,
                            Number = 1,
                            Row = "A",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 158,
                            IsAvailable = true,
                            Number = 2,
                            Row = "A",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 159,
                            IsAvailable = true,
                            Number = 3,
                            Row = "A",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 160,
                            IsAvailable = true,
                            Number = 4,
                            Row = "A",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 161,
                            IsAvailable = true,
                            Number = 5,
                            Row = "A",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 162,
                            IsAvailable = true,
                            Number = 6,
                            Row = "A",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 163,
                            IsAvailable = true,
                            Number = 7,
                            Row = "A",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 164,
                            IsAvailable = true,
                            Number = 8,
                            Row = "A",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 165,
                            IsAvailable = true,
                            Number = 1,
                            Row = "B",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 166,
                            IsAvailable = true,
                            Number = 2,
                            Row = "B",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 167,
                            IsAvailable = true,
                            Number = 3,
                            Row = "B",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 168,
                            IsAvailable = true,
                            Number = 4,
                            Row = "B",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 169,
                            IsAvailable = true,
                            Number = 5,
                            Row = "B",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 170,
                            IsAvailable = true,
                            Number = 6,
                            Row = "B",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 171,
                            IsAvailable = true,
                            Number = 7,
                            Row = "B",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 172,
                            IsAvailable = true,
                            Number = 8,
                            Row = "B",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 173,
                            IsAvailable = true,
                            Number = 1,
                            Row = "C",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 174,
                            IsAvailable = true,
                            Number = 2,
                            Row = "C",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 175,
                            IsAvailable = true,
                            Number = 3,
                            Row = "C",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 176,
                            IsAvailable = true,
                            Number = 4,
                            Row = "C",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 177,
                            IsAvailable = true,
                            Number = 5,
                            Row = "C",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 178,
                            IsAvailable = true,
                            Number = 6,
                            Row = "C",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 179,
                            IsAvailable = true,
                            Number = 7,
                            Row = "C",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 180,
                            IsAvailable = true,
                            Number = 8,
                            Row = "C",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 181,
                            IsAvailable = true,
                            Number = 1,
                            Row = "D",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 182,
                            IsAvailable = true,
                            Number = 2,
                            Row = "D",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 183,
                            IsAvailable = true,
                            Number = 3,
                            Row = "D",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 184,
                            IsAvailable = true,
                            Number = 4,
                            Row = "D",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 185,
                            IsAvailable = true,
                            Number = 5,
                            Row = "D",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 186,
                            IsAvailable = true,
                            Number = 6,
                            Row = "D",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 187,
                            IsAvailable = true,
                            Number = 7,
                            Row = "D",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 188,
                            IsAvailable = true,
                            Number = 8,
                            Row = "D",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 189,
                            IsAvailable = true,
                            Number = 1,
                            Row = "E",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 190,
                            IsAvailable = true,
                            Number = 2,
                            Row = "E",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 191,
                            IsAvailable = true,
                            Number = 3,
                            Row = "E",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 192,
                            IsAvailable = true,
                            Number = 4,
                            Row = "E",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 193,
                            IsAvailable = true,
                            Number = 5,
                            Row = "E",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 194,
                            IsAvailable = true,
                            Number = 6,
                            Row = "E",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 195,
                            IsAvailable = true,
                            Number = 7,
                            Row = "E",
                            TheaterId = 3
                        },
                        new
                        {
                            Id = 196,
                            IsAvailable = true,
                            Number = 8,
                            Row = "E",
                            TheaterId = 3
                        });
                });

            modelBuilder.Entity("H3Project.Data.Models.Theater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.ToTable("Theaters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CinemaId = 1,
                            Name = "Screen 1"
                        },
                        new
                        {
                            Id = 2,
                            CinemaId = 1,
                            Name = "Screen 2"
                        },
                        new
                        {
                            Id = 3,
                            CinemaId = 2,
                            Name = "Screen 1"
                        });
                });

            modelBuilder.Entity("H3Project.Data.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 12.99m,
                            PurchaseDate = new DateTime(2025, 1, 4, 10, 7, 14, 93, DateTimeKind.Local).AddTicks(8346),
                            ScheduleId = 1,
                            SeatId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Price = 14.99m,
                            PurchaseDate = new DateTime(2025, 1, 6, 10, 7, 14, 96, DateTimeKind.Local).AddTicks(6109),
                            ScheduleId = 2,
                            SeatId = 98,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Price = 9.99m,
                            PurchaseDate = new DateTime(2025, 1, 8, 10, 7, 14, 96, DateTimeKind.Local).AddTicks(6131),
                            ScheduleId = 3,
                            SeatId = 157,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("H3Project.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserRoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john@example.com",
                            PasswordHash = "hashed_password_1",
                            UserRoleId = 1,
                            Username = "john_doe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane@example.com",
                            PasswordHash = "hashed_password_2",
                            UserRoleId = 2,
                            Username = "jane_smith"
                        },
                        new
                        {
                            Id = 3,
                            Email = "alice@example.com",
                            PasswordHash = "hashed_password_3",
                            UserRoleId = 2,
                            Username = "alice_jones"
                        });
                });

            modelBuilder.Entity("H3Project.Data.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.HasOne("H3Project.Data.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("H3Project.Data.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("H3Project.Data.Models.Schedule", b =>
                {
                    b.HasOne("H3Project.Data.Models.Movie", "Movie")
                        .WithMany("Schedules")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("H3Project.Data.Models.Theater", "Theater")
                        .WithMany("Schedules")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("H3Project.Data.Models.Seat", b =>
                {
                    b.HasOne("H3Project.Data.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId");

                    b.HasOne("H3Project.Data.Models.Theater", "Theater")
                        .WithMany("Seats")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("H3Project.Data.Models.Theater", b =>
                {
                    b.HasOne("H3Project.Data.Models.Cinema", "Cinema")
                        .WithMany("Theaters")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("H3Project.Data.Models.Ticket", b =>
                {
                    b.HasOne("H3Project.Data.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("H3Project.Data.Models.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("H3Project.Data.Models.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("H3Project.Data.Models.User", b =>
                {
                    b.HasOne("H3Project.Data.Models.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("H3Project.Data.Models.Cinema", b =>
                {
                    b.Navigation("Theaters");
                });

            modelBuilder.Entity("H3Project.Data.Models.Movie", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("H3Project.Data.Models.Theater", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("H3Project.Data.Models.User", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
